### ISSUE TITLE
Feedback for /learn/css/sass-functions

### ISSUE THREAD

**Issue by andreacarlota** [mica-web/mica-web.github.io#15]
> **NOTE:** If you followed a link from the course web site, the title above should automatically include the URL for the page you were on. If not, please note the page URL here: 

### About this feedback
👀 I have identified:
* [ ] A broken link
* [ ] Content that is incorrect (including typos)
* [ ] Content that is confusing
* [ ] A layout/CSS bug
* [X ] Something else

### What needs to be fixed
> Describe the existing content. You can copy and paste the existing text or link here, for example.
When I'm in the Glitch project preview of Learn Sass: Color Functions 
and I click the links of documentation and related links the glitch preview becomes gray and says "This content is blocked. Contact the site owner to fix the issue."

### Possible solutions
> Let me know what would fix the current content.

### Additional context
> Anything else that would be helpful for me to know in order to fix this issue. If you're describing a layout or CSS bug, here it would be helpful to note your operating system and web browser. You can visit this link: http://supportdetails.net/ and copy the URL under "Share these details" to provide an extra-credit level of information. 🙏🏻

**Comment by angeliquejw** [comment]
Thanks for making me aware of this, @andreacarlota -- The issue should now be fixed 🤞🏻

Since the code to fix this happened on Glitch, there is no related PR or changes to this repo; the updated Glitch project is here: https://glitch.com/~sass-color-functions and can be seen on the live site on this page: https://mica-web.github.io/learn/css/sass-functions
